services:
  - type: worker
    name: keyword-search-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: LOG_CHANNEL_ID
        sync: false
